<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="7729" started-at="2018-09-19T14:15:37Z" finished-at="2018-09-19T14:15:44Z">
    <groups>
    </groups>
    <test name="SalesOrder" duration-ms="7729" started-at="2018-09-19T14:15:37Z" finished-at="2018-09-19T14:15:44Z">
      <class name="TestRestAPI.SalesOrder.listTransactionSummaryforSourceBid">
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:TestRestAPI.SalesOrder.listTransactionSummaryforSourceBid@dc24521]" name="beforeMethod" is-config="true" duration-ms="390" started-at="2018-09-19T10:15:37Z" finished-at="2018-09-19T10:15:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void TestRestAPI.SalesOrder.listTransactionSummaryforSourceBid.MTC001_VerifyResponseForValid_MstrCustID_accept_JSON() throws java.io.IOException,java.sql.SQLException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="MTC001_VerifyResponseForValid_MstrCustID_accept_JSON()[pri:0, instance:TestRestAPI.SalesOrder.listTransactionSummaryforSourceBid@dc24521]" name="MTC001_VerifyResponseForValid_MstrCustID_accept_JSON" duration-ms="6230" started-at="2018-09-19T10:15:37Z" description="This test would verify response for valid input parameters as MstrCustID in request." finished-at="2018-09-19T10:15:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MTC001_VerifyResponseForValid_MstrCustID_accept_JSON -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:TestRestAPI.SalesOrder.listTransactionSummaryforSourceBid@dc24521]" name="afterMethod" is-config="true" duration-ms="577" started-at="2018-09-19T10:15:43Z" finished-at="2018-09-19T10:15:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=MTC001_VerifyResponseForValid_MstrCustID_accept_JSON status=SUCCESS method=listTransactionSummaryforSourceBid.MTC001_VerifyResponseForValid_MstrCustID_accept_JSON()[pri:0, instance:TestRestAPI.SalesOrder.listTransactionSummaryforSourceBid@dc24521] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:TestRestAPI.SalesOrder.listTransactionSummaryforSourceBid@dc24521]" name="beforeMethod" is-config="true" duration-ms="16" started-at="2018-09-19T10:15:44Z" finished-at="2018-09-19T10:15:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void TestRestAPI.SalesOrder.listTransactionSummaryforSourceBid.MTC002_VerifyResponseForValid_MstrCustID_accept_XML() throws java.io.IOException,java.sql.SQLException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="MTC002_VerifyResponseForValid_MstrCustID_accept_XML()[pri:0, instance:TestRestAPI.SalesOrder.listTransactionSummaryforSourceBid@dc24521]" name="MTC002_VerifyResponseForValid_MstrCustID_accept_XML" duration-ms="375" started-at="2018-09-19T10:15:44Z" description="This test would verify response for valid input parameters as MstrCustID in request." finished-at="2018-09-19T10:15:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [12345] but found [143312]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [12345] but found [143312]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at TestRestAPI.SalesOrder.listTransactionSummaryforSourceBid.MTC002_VerifyResponseForValid_MstrCustID_accept_XML(listTransactionSummaryforSourceBid.java:333)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MTC002_VerifyResponseForValid_MstrCustID_accept_XML -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:TestRestAPI.SalesOrder.listTransactionSummaryforSourceBid@dc24521]" name="afterMethod" is-config="true" duration-ms="94" started-at="2018-09-19T10:15:44Z" finished-at="2018-09-19T10:15:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=MTC002_VerifyResponseForValid_MstrCustID_accept_XML status=FAILURE method=listTransactionSummaryforSourceBid.MTC002_VerifyResponseForValid_MstrCustID_accept_XML()[pri:0, instance:TestRestAPI.SalesOrder.listTransactionSummaryforSourceBid@dc24521] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- TestRestAPI.SalesOrder.listTransactionSummaryforSourceBid -->
    </test> <!-- SalesOrder -->
  </suite> <!-- Suite -->
</testng-results>
